<!DOCTYPE html>
  <html lang="en">
  <head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CRUD Example</title>
  <style>
      /* CSS styles for layout */
      body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
      }
      .container {
          max-width: 600px;
          margin: 20px auto;
          padding: 20px;
          border: 1px solid #ccc;
          border-radius: 5px;
      }
      ul {
          list-style-type: none;
          padding: 0;
      }
      li {
          margin-bottom: 10px;
      }
      button {
          margin-top: 10px;
      }
  </style>
  </head>
  <body>
  
  <div class="container">
      <h2>CRUD Example</h2>
      <input type="text" id="itemInput" placeholder="Enter an item">
      <button onclick="addItem()">Add Item</button>
      <ul id="itemList"></ul>
  </div>
  
  <script>
      // JavaScript code for CRUD operations
      let items = [];
  
      function addItem() {
          let newItem = document.getElementById('itemInput').value.trim();
          if (newItem !== '') {
              items.push(newItem);
              displayItems();
              document.getElementById('itemInput').value = '';
          }
      }
  
      function displayItems() {
          let itemList = document.getElementById('itemList');
          itemList.innerHTML = '';
          items.forEach(function(item, index) {
              let li = document.createElement('li');
              li.innerHTML = `${item} <button onclick="editItem(${index})">Edit</button> <button onclick="deleteItem(${index})">Delete</button>`;
              itemList.appendChild(li);
          });
      }
  
      function editItem(index) {
          let editedItem = prompt('Edit item:', items[index]);
          if (editedItem !== null && editedItem.trim() !== '') {
              items[index] = editedItem.trim();
              displayItems();
          }
      }
  
      function deleteItem(index) {
          if (confirm('Are you sure you want to delete this item?')) {
              items.splice(index, 1);
              displayItems();
          }
      }
  
      // Initial display
      displayItems();
  </script>
  
  </body>
  </html>
